services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - data:/app/data
    environment:
      - DATABASE_URL=postgresql+psycopg2://user:password@db:5432/uploads

  db:
    image: postgres:16
    container_name: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: uploads
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  watcher:
    build:
      context: ./watcher
      dockerfile: Dockerfile
    volumes:
      - data:/watcher/data
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql+psycopg2://user:password@db:5432/uploads
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 6h & wait $${!}; certbot renew; done;'"

volumes:
  data:
  db_data:
